DICTNAMES = [
    'marquez', 'vinales', 'Marc Marquez', 'maverick', 'dovi', 'dovizioso', 'dovicioso', 'rossi', 'rins', 'miller',
    'jack'
]

REGEX_PILOTS = {
                   'Marc Marquez*': 'Marquez',
                   'Marquez*': 'Marquez',
                   'Márque*': 'Marquez',
                   'márque*': 'Marquez',
                   'marc marquez*': 'Marquez',
                   'marque*': 'Marquez',
                   'Andrea Dovizioso*': 'Dovi',
                   'Dovi*': 'Dovi',
                   'dovi*': 'Dovi',
                   'Zarco*': 'Zarco',
                   'zarco*': 'Zarco',
                   'Petrux*': 'Petrucci',
                   'Petrucci*': 'Petrucci',
                   'Petruci*': 'Petrucci',
                   'petrux*': 'Petrucci',
                   'petrucci*': 'Petrucci',
                   'petruci*': 'Petrucci',
                   'Maverick Vi[a-z]ales*': 'Viñales',
                   'Maverick*': 'Viñales',
                   'Viñales*': 'Viñales',
                   'Maveric*': 'Viñales',
                   'maverick vi[a-z]ales*': 'Viñales',
                   'maverick*': 'Viñales',
                   'maveric*': 'Viñales',
                   'Iannone*': 'Iannone',
                   'Ianone*': 'Iannone',
                   'iannone*': 'Iannone',
                   'ianone*': 'Iannone',
                   'Mir*': 'Mir',
                   'mir*': 'Mir',
                   'Aleix Espargaro*': 'Aleix',
                   'Alex Rins*': 'Rins',
                   'Rins*': 'Rins',
                   'alex rins*': 'Rins',
                   'rins*': 'Rins',
                   'Miller*': 'Miller',
                   'miller*': 'Miller',
                   'Jack Miller*': 'Miller',
                   'jack miller*': 'Miller',
                   'Pol Espargar*': 'Pol',
                   'pol espargar*': 'Pol',
                   'Valentino Rossi*': 'Rossi',
                   'Ros*i': 'Rossi',
                   'ros*i': 'Rossi',
                   'valentino rossi*': 'Rossi',
                   'valentino rosi*': 'Rossi',
                   'pirro*': 'Pirro',
                   'Pirro*': 'Pirro',
                   'Hafizh Syahrin*': 'Syahrin',
                   'Syahrin*': 'Syahrin',
                   'syahrin*': 'Syahrin',
                   'shyarin*': 'Syahrin',
                   'Bagnaia*': 'Bagnaia',
                   'bagnaia*': 'Bagnaia',
                   'Oliveira*': 'Oliveira',
                   'oliveira*': 'Oliveira',
                   'lorenzo*': 'Lorenzo',
                   'Lorenzo*': 'Lorenzo',
                   'quartanar*': 'Quartanaro',
                   'Quartanar*': 'Quartanaro',
                   'Quartarar*': 'Quartanaro', 'quartarar*': 'Quartanaro'
}

REGEX_POSITIONS = {
    'pole': 'pole',
    'Pole': 'pole',
    'vr': 'vr',
    'Vr': 'vr',
    'VR': 'vr',
    'vR': 'vr',
    'Vuelta rápida': 'vr',
    'Vuelta Rápida': 'vr',
    'vuelta rápida': 'vr',
    '1': '1',
    '2': '2',
    '3': '3',
    'independiente': 'pi',
    'Independiente': 'pi',
    'Moto2': 'm2',
    'Moto3': 'm3',
    'moto2': 'm2',
    'moto3': 'm3'
}

