DICTNAMES = [
    'marquez', 'vinales', 'Marc Marquez', 'maverick', 'dovi', 'dovizioso', 'dovicioso', 'rossi', 'rins', 'miller',
    'jack'
]

REGEX_PILOTS = {
    'm.rque*': 'Marquez',
    'Andrea Dovizioso*': 'Dovi',
    'dovi*': 'Dovi',
    'zarco*': 'Zarco',
    'petru+i*': 'Petrucci',
    'petrux*': 'Petrucci',
    'vi.ales': 'Viñales',
    '\Drutchlow': 'Crutchlow',
    'ian*one': 'Iannone',
    'mir': 'Mir',
    'Aleix Espargaro*': 'Aleix',
    '\Dins': 'Rins',
    '\Dlex..ins': 'Rins',
    'Miller*': 'Miller',
    'miller*': 'Miller',
    'Jack Miller*': 'Miller',
    'jack miller*': 'Miller',
    'Pol Espargar*': 'Pol',
    'pol espargar*': 'Pol',
    'Valentino Rossi*': 'Rossi',
    'Ros*i': 'Rossi',
    'ros*i': 'Rossi',
    'valentino rossi*': 'Rossi',
    'valentino rosi*': 'Rossi',
    'pirro*': 'Pirro',
    'Pirro*': 'Pirro',
    'Hafizh Syahrin*': 'Syahrin',
    'Syahrin*': 'Syahrin',
    'syahrin*': 'Syahrin',
    'shyarin*': 'Syahrin',
    'Bagnaia*': 'Bagnaia',
    'bagnaia*': 'Bagnaia',
    'Oliveira*': 'Oliveira',
    'oliveira*': 'Oliveira',
    'lorenzo*': 'Lorenzo',
    'Lorenzo*': 'Lorenzo',
    'quarta.ar*': 'Quartararo',
    'Quarta.ar*': 'Quartararo',
    '\Desko': 'Jesko',
    '\Desko..affin': 'Jesko',
    '\Dukas..ulovic': 'Tulovic',
    '\Dulovic': 'Tulovic',
    '\Ddendaal': 'Odendaal',
    '\Docatel*i': 'Locatelli',
    'Balda': 'Baldassarri',
    'Baldassarri': 'Baldassarri',
    '\Dantra': 'Chantra',
    '\Darini': 'Marini',
    '\Drenas': 'Arenas',
    '\Dlbert..renas': 'Arenas',
    '\Dern.ndez': 'Fernandez',
    '\Dinder': 'Binder',
    '\Dvarro': 'Navarro',
    '.anet': 'Canet',
    '\Dalla..orta': 'Dallaporta',
    '\Drbolino': 'Arbolino',
    '\Duzuki': 'Suzuki',
}

REGEX_POSITIONS = {
    'pole': 'pole',
    'Pole': 'pole',
    'vr': 'vr',
    'Vr': 'vr',
    'VR': 'vr',
    'vR': 'vr',
    'Vuelta rápida': 'vr',
    'Vuelta Rápida': 'vr',
    'vuelta rápida': 'vr',
    "^1": '1',
    "^2": '2',
    "^3": '3',
    "^\n *1": '1',
    "^\n *2": '2',
    "^\n *3": '3',
    "^\r\n *1": '1',
    "^\r\n *2": '2',
    "^\r\n *3": '3',
    'independiente': 'pi',
    'Independiente': 'pi',
    '\Doto\s2': 'm2',
    '\Doto*2': 'm2',
    '\Doto\s3': 'm3',
    '\Doto*3': 'm3',
}

